# Etapa 1: Build
FROM node:20 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --configuration=production

# Etapa 2: Servidor Nginx
FROM nginx:alpine

# IMPORTANTE: Reemplaza 'ng-crud-card' por el nombre exacto de tu proyecto 
# que aparece en tu archivo angular.json (propiedad "outputPath")
COPY --from=build /app/dist/ng-crud-card/browser /usr/share/nginx/html

# Copiamos la configuración de nginx que creamos arriba
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]